### ISSUE TITLE
error resolving host and basepath

### ISSUE THREAD

**Issue by bruceadowns** [swaggo/swag#474] opened 2019-07-23 04:40 UTC
**Describe the bug**
The latest version (tips) of swag is not resolving host and base path.

i.e.
`curl -X GET "https://{{.Host}}{{.BasePath}}/api/version" -H  "accept: text/plain"`

**To Reproduce**
1. generate docs.go
2. compile
3. host swagger
4. See invalid url

**Expected behavior**
This:
`curl -X GET "https://{{.Host}}{{.BasePath}}/api/version" -H  "accept: text/plain"`

should be:
`curl -X GET "https://localhost:8443/api/version" -H  "accept: text/plain"`

**Screenshots**
![image](https://user-images.githubusercontent.com/1503908/61683082-01cb1080-acc9-11e9-9cf3-e71b17e9bed3.png)

**Your swag version**
~~1.5.1 - tips~~
tips

**Your go version**
1.12.7 - latest

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: firefox
 - Version: 68

**Additional context**

**Comment by ubogdan** [comment] 2019-07-23 08:25
Please update to [latest](https://github.com/swaggo/swag/releases) version (1.6.2) and let us know if this still happens.

**Comment by bruceadowns** [comment] 2019-07-23 15:10
To clarify, v1.5.1 and v1.6.2 work fine. The problem occurs when using tips.

**Comment by easonlin404** [comment] 2019-07-24 03:19
@bruceadowns How do you show swagger doc site? I think you directly use `swagger.json `or `swagger.ymal` generated by swag cliright? 

@ubogdan it's kind of a bug caused by programmatically setting values because swag output json/yaml but doesn't pass programmatically value to it.

**Comment by bruceadowns** [comment] 2019-07-24 04:49
I first get swag:
`go get github.com/swaggo/swag/cmd/swag`

then init:
`swag init -g cmd/cnc.go`

then route and host:
`router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)`

**Comment by ubogdan** [comment] 2019-07-25 08:34
@bruceadowns i have no clue how to download and test "tips" version . 
If you speak about lastest commit , I can certify  "it works on my computer" .
```
package main

import (
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
	"github.com/swaggo/swag/example/is461/docs"
	"net/http"
)

// @title GEO service
// @version 1.0
// @description Returns GEO information from a request.
// @description Something `wrapped`.
// @host localhost:1323
// @schemes http https
// @BasePath /

func main() {
	router := mux.NewRouter()
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	http.ListenAndServe(":8082", router)
}
```
curl -X POST "http://localhost:1323/testpost" -H "accept: application/json"

@easonlin404 swagger.json and swagger.yaml are generated according to annotation and they should not interfere with docs.go functionality/ability to set things at run time. right ?

**Comment by easonlin404** [comment] 2019-07-25 08:39
@ubogdan yep, you can view swagger.json generated by swag like: 
```
{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/version": {
            "get": {
                "description": "api version2",
                "summary": "api version1"
            }
        }
    }
}
```

and for description,version,host,basePath these fields cannot be  around by {{ .xxx}}.

**Comment by ubogdan** [comment] 2019-07-25 11:01
swagger.json and swagger.yaml are static files. That values ("{{.Title}}","{{.Description}}","{{.Version}}","{{.Host}}","{{.BasePath}}")should not be filled with any "default" so they will not be rendered into file at generation time.
As far as i understand this files are meant to be "delivered" to other apps that want yo integrate with the API you are developing. I'm saying this because this files doesn't get embedded in actual binary application.

**Comment by bruceadowns** [comment] 2019-07-25 14:53
> @bruceadowns i have no clue how to download and test "tips" version .
> If you speak about lastest commit , I can certify "it works on my computer" .

Yes, apologies, by tips I mean latest.

**Comment by bruceadowns** [comment] 2019-07-25 14:56
> // @host localhost:1323
> // @BasePath /

I was not setting @BasePath, so I've corrected that.

However, how am I expected to set @Host? That previously was not required and dynamic. Plus in will be different in my local environment versus in the staging and production pipelines.

**Comment by bruceadowns** [comment] 2019-07-25 15:03
Using the latest build I noticed differences in the generated docs/docs.go.

Transcript:

```
$ cd example/basic

$ ../../swag init
2019/07/25 07:58:29 Generate swagger docs....
2019/07/25 07:58:29 Generate general API Info, search dir:./
2019/07/25 07:58:29 Generating web.APIError
2019/07/25 07:58:29 Generating web.Pet
2019/07/25 07:58:29 Generating web.Tag
2019/07/25 07:58:29 Generating web.RevValue
2019/07/25 07:58:29 create docs.go at  docs/docs.go
2019/07/25 07:58:29 create swagger.json at  docs/swagger.json
2019/07/25 07:58:29 create swagger.yaml at  docs/swagger.yaml

$ git diff docs/docs.go 
diff --git a/example/basic/docs/docs.go b/example/basic/docs/docs.go
index 5d43686..98fa8d9 100644
--- a/example/basic/docs/docs.go
+++ b/example/basic/docs/docs.go
@@ -1,6 +1,6 @@
 // GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
 // This file was generated by swaggo/swag at
-// 2019-07-17 15:34:26.038643394 +0300 EEST m=+0.024553500
+// 2019-07-25 07:58:29.925335 -0700 PDT m=+0.022096827
 
 package docs
 
@@ -16,8 +16,8 @@ var doc = `{
     "schemes": {{ marshal .Schemes }},
     "swagger": "2.0",
     "info": {
-        "description": "This is a sample server Petstore server.",
-        "title": "Swagger Example API",
+        "description": "{{.Description}}",
+        "title": "{{.Title}}",
         "termsOfService": "http://swagger.io/terms/",
         "contact": {
             "name": "API Support",
@@ -28,10 +28,10 @@ var doc = `{
             "name": "Apache 2.0",
             "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
         },
-        "version": "1.0"
+        "version": "{{.Version}}"
     },
-    "host": "petstore.swagger.io",
-    "basePath": "/v2",
+    "host": "{{.Host}}",
+    "basePath": "{{.BasePath}}",
     "paths": {
         "/file/upload": {
             "post": {
@@ -273,7 +273,14 @@ type swaggerInfo struct {
 }
 
 // SwaggerInfo holds exported Swagger Info so clients can modify it
-var SwaggerInfo = swaggerInfo{Schemes: []string{}}
+var SwaggerInfo = swaggerInfo{
+       Version:     "1.0",
+       Host:        "petstore.swagger.io",
+       BasePath:    "/v2",
+       Schemes:     []string{},
+       Title:       "Swagger Example API",
+       Description: "This is a sample server Petstore server.",
+}
 
 type s struct{}
```

**Comment by bruceadowns** [comment] 2019-07-26 02:11
If I take out the @host annotation from /swaggo/swag/example/basic/main.go, here is the generated docs.go file:

```
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "{{.Host}}",
	BasePath:    "/v2",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "This is a sample server Petstore server.",
}
```

Because @Host is not annotated, it is incorrectly set to "{{.Host}}".

**Comment by ubogdan** [comment] 2019-07-26 11:13
I think you are still sussing the broken version . The PR was merged into master 8 hours ago. The generated output for example basic should be
```
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-07-26 14:03:36.965041399 +0300 EEST m=+0.034665644


// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "This is a sample server Petstore server.",
}
```

**Comment by bruceadowns** [comment] 2019-07-26 15:14
> I think you are still using the broken version . The PR was merged into master 8 hours ago.

yup, latest changes lgtm.

**Comment by ubogdan** [comment] 2019-07-27 14:21
Thanks for your feedback @bruceadowns !

**Closed by ubogdan** 2019-07-27 14:21 UTC
Labels: bug
