### ISSUE TITLE
how to build right json。

### ISSUE THREAD

**Issue by dustess-encrypt** [swaggo/swag#753] opened 2020-07-17 12:34 UTC
**Describe the bug**
i got a not right json,i have a struct like this.
type Response struct {
	Data     []map[string]interface{}       `json:"data"`
}

run swag init

 "data": {
                    "type": "array",
                    "items": {
                        "type": "\u0026{%!s(token.Pos=1283) string %!s(*ast.InterfaceType=\u0026{1294 0xc0002c76b0 false})}"
                    }
                },

what the happen?

my swag version
github.com/swaggo/gin-swagger v1.2.0
github.com/swaggo/swag v1.6.7

**Comment by sdghchj** [comment] 2020-07-17 15:05
I can't reproduce it.

**Comment by ubogdan** [comment] 2021-09-28 19:51
Closing: outdated.

**Closed** 2021-09-28 19:54 UTC
