### ISSUE TITLE
swag init could not find struct from imported package

### ISSUE THREAD

**Issue by alirezastack** [swaggo/swag#1300] opened 2022-08-20 12:51 UTC
**Describe the bug**
I'm trying to provide a struct as request body to `@Param request body`, but the issue is that the struct is imported from another package and not present in current project. So for instance:

```
import (
models "git.mySite.net/core/sample-models"
)

```
And in my function I use:
`var profile models.UserProfile`

Before my function I use swagger annotation:

`// @Param request body models.UserProfile true "query params"`

But it does not work. I have tried many different formats but with no luck.

**To Reproduce**
1. Define a Go package with some struct
2. Import your struct in your function and use it also as `@Param`
3. issue the command: `swag init`

You will get the below error:

```
2022/08/20 16:53:34 Generate swagger docs....
2022/08/20 16:53:34 Generate general API Info, search dir:./
2022/08/20 16:53:35 ParseComment error in file /Users/Username/GolandProjects/myProject/controller/sample_controller.go :cannot find type definition: models.UserProfile
```

**Expected behavior**
Successful document generation with no error.

**Your swag version**
1.8.4

**Your go version**
1.18.4

**Desktop (please complete the following information):**
 - OS: Mac OS X 12.1
 - Browser: Opera
 - Version: 89.0

**Comment by capcom6** [comment] 2022-08-23 11:01
Hello!

Try using the actual package name, not an alias:

```go
// @Param request body sample-models.UserProfile true "query params"
```

I think, swag doesn't support aliases for packages.

Duplicate of https://github.com/swaggo/swag/issues/1291

**Comment by sdghchj** [comment] 2022-08-25 01:36
if `git.mySite.net/core/sample-models` is not inside your project directory, you have to import it into your `main` package.
```
//main.go

import(
    _  "git.mySite.net/core/sample-models"
)

````

then

`
swag init  --parseDependency ……
`

**Closed** 2022-08-27 05:50 UTC

**Comment by mailtokun** [comment] 2022-09-16 10:14
```
 swag init  --pd   
2022/09/16 18:13:56 Generate swagger docs....
2022/09/16 18:13:56 Generate general API Info, search dir:./
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x141c928]

goroutine 1 [running]:
github.com/swaggo/swag.(*PackagesDefinitions).parseFunctionScopedTypesFromFile(0xc00000ea50, 0xc000bd2c80, {0xc0003b7c20, 0x18}, 0xc0023ab6e0)
        /Users/yangkun/dev/pkg/mod/github.com/swaggo/swag@v1.8.5/packages.go:168 +0xa8
github.com/swaggo/swag.(*PackagesDefinitions).ParseTypes(0xc00000ea50)
        /Users/yangkun/dev/pkg/mod/github.com/swaggo/swag@v1.8.5/packages.go:110 +0xc9
github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0xc0001ce2a0, {0xc0001fa060, 0x1, 0x0}, {0x1512a84, 0x7}, 0x64)
        /Users/yangkun/dev/pkg/mod/github.com/swaggo/swag@v1.8.5/parser.go:362 +0x3da
github.com/swaggo/swag/gen.(*Gen).Build(0xc0001c7980, 0xc0001cd6c0)
        /Users/yangkun/dev/pkg/mod/github.com/swaggo/swag@v1.8.5/gen/gen.go:177 +0x5af
main.initAction(0xc00019b8c0)
        /Users/yangkun/dev/pkg/mod/github.com/swaggo/swag@v1.8.5/cmd/swag/main.go:151 +0x6f7
github.com/urfave/cli/v2.(*Command).Run(0xc0001997a0, 0xc0001dc400)
        /Users/yangkun/dev/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc0001d4340, {0x15be130, 0xc00002e090}, {0xc0000201b0, 0x3, 0x3})
        /Users/yangkun/dev/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/yangkun/dev/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /Users/yangkun/dev/pkg/mod/github.com/swaggo/swag@v1.8.5/cmd/swag/main.go:221 +0x55d
```

**Comment by omgupta1608** [comment] 2024-01-16 07:12
Did anyone find a solution to this?
