### ISSUE TITLE
cannot find all dependencies, unable to resolve root package?

### ISSUE THREAD

**Issue by benyu** [swaggo/swag#909] opened 2021-04-07 08:07 UTC
**Describe the bug**
github.com/name/project/app/modA/api cannot find all dependencies, unable to resolve root packag

** The struct of proejct looks like **

+project
+-internal
+--token
+--others
+-app
+--modA
|----internal
|---main.go
|-go.mod
|-go.sum

**To Reproduce**
// current path project root
go env -w GO111MODULE="on"
swag init -g app/mod/api/main.go  --parseDependency --parseInternal

**Your swag version**
swag version v1.7.0

**Your go version**
go 1.16 dawin/amd64

**Comment by davisford** [comment] 2021-04-15 15:22
I'm having the same issue -- this used to work fine.  The only thing that changed _I think_ is that I updated my go version recently.  Current version I am on is `go version go1.16.3 darwin/amd64`

**Comment by tianhaopx** [comment] 2021-05-07 06:37
if local go version is different from the version used to compile and build swag, you need to compile and build swag again. I think this issue is caused by swag's dependency package depth, see https://github.com/KyleBanks/depth/issues/15

**Comment by ilyulev** [comment] 2021-06-24 22:16
For me the problem was resolved with executing: `go get github.com/swaggo/swag/cmd/swag`

**Comment by adampresley** [comment] 2021-07-01 00:48
The solution from @ilyulev solve it for me as well.

**Closed** 2021-08-24 21:35 UTC

**Comment by ahuigo** [comment] 2022-04-14 04:47
> For me the problem was resolved with executing: `go get github.com/swaggo/swag/cmd/swag`

I use go1.17, and I solved it by:
`go install github.com/swaggo/swag/cmd/swag@latest`
